# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 13:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('cellphone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('volunteer_or_not', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AbilityTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=50, verbose_name='活动名称')),
                ('campaign_type', models.CharField(choices=[('1', '小组类'), ('2', '活动类'), ('3', '其他')], max_length=50, verbose_name='活动分类')),
                ('campaign_date', models.DateTimeField(verbose_name='活动时间')),
                ('campaign_client', models.CharField(max_length=50, verbose_name='服务对象')),
                ('campaign_address', models.CharField(max_length=50, verbose_name='活动地点')),
                ('campaign_content', models.CharField(max_length=255, verbose_name='活动内容')),
                ('campaign_paid', models.CharField(max_length=50, verbose_name='服务费用')),
                ('campaign_signup_deadline', models.DateTimeField(verbose_name='报名截止时间')),
                ('campaign_contact', models.CharField(max_length=50, verbose_name='活动联系方式')),
                ('campaign_counts', models.PositiveSmallIntegerField(verbose_name='可报名总人数')),
            ],
            options={
                'verbose_name_plural': '公益活动',
            },
        ),
        migrations.CreateModel(
            name='PolicyQA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qa_title', models.CharField(max_length=255, verbose_name='提问标题')),
                ('qa_content', models.CharField(max_length=255, verbose_name='提问内容')),
                ('qa_answer', models.CharField(max_length=255, verbose_name='回答')),
                ('qa_ask_date', models.DateTimeField(blank=True, null=True, verbose_name='提问时间')),
                ('qa_answer_date', models.DateTimeField(blank=True, null=True, verbose_name='回答时间')),
                ('qa_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '政策咨询',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalAdvice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proadv_question_title', models.CharField(max_length=255, verbose_name='咨询问题')),
                ('proadv_question_content', models.CharField(max_length=255, verbose_name='咨询内容')),
                ('proadv_full_name', models.CharField(max_length=10, verbose_name='姓名')),
                ('proadv_sex', models.CharField(choices=[('1', '男'), ('2', '女')], max_length=1, verbose_name='性别')),
                ('proadv_age', models.CharField(blank=True, max_length=20, verbose_name='年龄')),
                ('proadv_house_hold', models.CharField(blank=True, max_length=50, verbose_name='户籍所在地')),
                ('proadv_id_num', models.CharField(blank=True, max_length=50, verbose_name='身份证明')),
                ('proadv_ethnic', models.CharField(blank=True, max_length=50, verbose_name='民族')),
                ('proadv_political_status', models.CharField(blank=True, max_length=50, verbose_name='政治面貌')),
                ('proadv_religion', models.CharField(blank=True, max_length=50, verbose_name='宗教')),
                ('proadv_occupation', models.CharField(blank=True, max_length=50, verbose_name='职业')),
                ('proadv_studying_grade', models.CharField(blank=True, max_length=50, verbose_name='就读年级')),
                ('proadv_degree_of_education', models.CharField(blank=True, max_length=50, verbose_name='文化程度')),
                ('proadv_community', models.CharField(blank=True, max_length=50, verbose_name='所在社区')),
                ('proadv_contact', models.CharField(blank=True, max_length=11, verbose_name='联系方式(手机)')),
                ('proadv_live_address', models.CharField(blank=True, max_length=50, verbose_name='家庭住址')),
                ('proadv_marriage', models.CharField(blank=True, choices=[('1', '单身'), ('2', '同居'), ('3', '已婚'), ('4', '分居'), ('5', '离婚'), ('6', '丧偶'), ('7', '其它')], max_length=1, verbose_name='婚姻状况')),
                ('proadv_from', models.CharField(max_length=255, verbose_name='个案来源')),
                ('proadv_rescue_methods', models.CharField(max_length=255, verbose_name='求助方法')),
                ('proadv_question_type', models.CharField(blank=True, choices=[('1', '亲子关系问题'), ('2', '婚姻问题'), ('3', '家庭纠纷'), ('4', '经济问题'), ('5', '职业问题'), ('6', '住屋问题'), ('7', '家庭暴力致伤/死(受害对象: 子女 / 配偶 / 老人 / 其它______)'), ('8', '个人精神/情绪问题'), ('9', '个人行为问题(吸毒/酒/赌博)'), ('10', '恋爱/交友问题'), ('11', '患病/复康问题(病类)'), ('12', '未婚怀孕'), ('13', '收养'), ('14', '其它')], max_length=50, verbose_name='咨询问题类型')),
                ('proadv_social_rescue', models.CharField(blank=True, choices=[('1', '医疗救助'), ('2', '教育救助'), ('3', '住房救助'), ('4', '临时救助'), ('5', '最低生活保障救助'), ('6', '其它')], max_length=50, verbose_name='社会救助')),
                ('proadv_result', models.CharField(blank=True, choices=[('1', '问题改善/解决结案'), ('2', '转为辅导个案'), ('3', '转介')], max_length=1, verbose_name='咨询结果')),
                ('proadv_sw_name', models.CharField(max_length=50, verbose_name='社工姓名')),
                ('proadv_case_id', models.CharField(max_length=50, verbose_name='个案编号')),
                ('proadv_date', models.DateField(verbose_name='咨询日期')),
                ('proadv_serv_date', models.DateField(verbose_name='服务日期')),
                ('proadv_serv_time', models.TimeField(verbose_name='服务时间')),
                ('proadv_serv_localtion', models.CharField(max_length=255, verbose_name='服务地点')),
                ('proadv_serv_counts', models.PositiveSmallIntegerField(default=0, verbose_name='服务次数')),
                ('proadv_serv_type', models.CharField(max_length=255, verbose_name='服务方式')),
                ('proadv_serv_content', models.TextField(verbose_name='服务内容')),
                ('proadv_status', models.BooleanField(default=True, verbose_name='个案状态')),
                ('proadv_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '专业咨询列表',
            },
        ),
        migrations.CreateModel(
            name='SingleUploadImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_or_service_name', models.CharField(max_length=50, verbose_name='活动名称')),
                ('photo_name', models.CharField(max_length=10, verbose_name='照片名字')),
                ('photo', models.ImageField(upload_to='media', verbose_name='图片')),
            ],
            options={
                'verbose_name_plural': '单图片上传',
            },
        ),
        migrations.CreateModel(
            name='VolunteerRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='photos',
            field=models.ManyToManyField(blank=True, to='api.SingleUploadImg', verbose_name='活动图片'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='signup_user_list',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='报名人员名单'),
        ),
    ]
