# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaignperson',
            options={'verbose_name_plural': '公益活动报名人'},
        ),
        migrations.AlterField(
            model_name='campaignperson',
            name='campaign_person_sex',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], max_length=1, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='professionaladvice',
            name='proadv_sex',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], max_length=1, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='volunteerinformation',
            name='volinfo_sex',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], max_length=1, verbose_name='性别'),
        ),
    ]
