# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-02 18:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyqa',
            name='qa_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policyqas', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
