# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-01 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignperson',
            name='campaign',
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_person',
            field=models.ManyToManyField(blank=True, related_name='报名人员名单', to='api.CampaignPerson', verbose_name='报名人员名单'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_volunteer',
            field=models.ManyToManyField(blank=True, to='api.VolunteerInformation', verbose_name='报名志愿者名单'),
        ),
        migrations.AlterField(
            model_name='campaignperson',
            name='campaign_person_sex',
            field=models.CharField(choices=[('1', '男'), ('2', '女')], max_length=1, verbose_name='性别'),
        ),
    ]
