# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180228_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleuploadimg',
            name='photo',
            field=models.ImageField(upload_to='', verbose_name='图片'),
        ),
    ]
