# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-02 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180203_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyqa',
            name='qa_answer',
            field=models.TextField(blank=True, null=True, verbose_name='回答'),
        ),
    ]
