# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180228_0511'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignSignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': '公益活动报名清单',
            },
        ),
        migrations.RemoveField(
            model_name='volunteerservice',
            name='signup_user_list',
        ),
        migrations.AlterModelOptions(
            name='campaign',
            options={'verbose_name_plural': '公益活动信息'},
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='signup_user_list',
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_vol_counts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='可报名志愿者人数'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='VolunteerService',
        ),
        migrations.AddField(
            model_name='campaignsignup',
            name='campaign_info',
            field=models.ManyToManyField(blank=True, to='api.Campaign', verbose_name='公益活动信息'),
        ),
        migrations.AddField(
            model_name='campaignsignup',
            name='campaign_person',
            field=models.ManyToManyField(blank=True, to='api.CampaignPerson', verbose_name='报名人员名单'),
        ),
        migrations.AddField(
            model_name='campaignsignup',
            name='campaign_volunteer',
            field=models.ManyToManyField(blank=True, to='api.VolunteerInformation', verbose_name='报名人员名单'),
        ),
    ]
