# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-01 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180302_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='campaign_content',
            field=models.TextField(verbose_name='活动内容'),
        ),
    ]
