# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180228_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignsignup',
            name='campaign_volunteer',
            field=models.ManyToManyField(blank=True, to='api.VolunteerInformation', verbose_name='报名志愿者名单'),
        ),
        migrations.AlterField(
            model_name='policyqa',
            name='qa_content',
            field=models.TextField(verbose_name='提问内容'),
        ),
        migrations.AlterField(
            model_name='policyqa',
            name='qa_marriage',
            field=models.CharField(blank=True, choices=[('1', '单身'), ('2', '同居'), ('3', '已婚'), ('4', '分居'), ('5', '离婚'), ('6', '丧偶'), ('7', '其它')], max_length=1, null=True, verbose_name='婚姻状况'),
        ),
    ]
