# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-01 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180302_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abilitytraining',
            name='at_content',
            field=models.TextField(verbose_name='培训内容'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_certified_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='志愿活动认证时数（小时）'),
        ),
    ]
