# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180228_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyqa',
            name='qa_o2o',
            field=models.CharField(choices=[('1', '线上'), ('2', '线下')], max_length=1, verbose_name='线上线下回复'),
        ),
    ]
