# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-01 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180302_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abilitytraining',
            name='at_counts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='可报名人数'),
        ),
    ]
