# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-01 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180302_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionaladvice',
            name='proadv_contact',
            field=models.CharField(max_length=11, verbose_name='联系方式(手机)'),
        ),
    ]
