# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180302_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignperson',
            name='campaign_person_sex',
            field=models.CharField(choices=[('1', '男'), ('2', '女')], default=1, max_length=1, verbose_name='性别'),
        ),
    ]
