# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180228_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyqa',
            name='qa_sex',
            field=models.CharField(choices=[('1', '男'), ('2', '女')], max_length=1, verbose_name='性别'),
        ),
    ]
