# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 05:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180303_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_information_name', models.CharField(max_length=50, verbose_name='姓名')),
                ('user_information_sex', models.CharField(choices=[('1', '男'), ('2', '女')], default=1, max_length=1, verbose_name='性别')),
                ('user_information_cellphone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('user_information_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('user_information_volunteer', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': '用户基本信息',
            },
        ),
        migrations.RemoveField(
            model_name='campaignperson',
            name='campaign_person_user',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '账户管理'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='cellphone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='volunteer_or_not',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_person',
            field=models.ManyToManyField(blank=True, related_name='campaign_members', to=settings.AUTH_USER_MODEL, verbose_name='报名人员名单'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_volunteer',
            field=models.ManyToManyField(blank=True, related_name='campaign_volunteers', to='api.VolunteerInformation', verbose_name='报名志愿者名单'),
        ),
        migrations.DeleteModel(
            name='CampaignPerson',
        ),
        migrations.AddField(
            model_name='userinformation',
            name='user_information_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaignperson', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
