# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180228_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyqa',
            name='qa_status',
            field=models.BooleanField(default=False, verbose_name='咨询状态'),
        ),
    ]
