# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_policyqa_qa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionaladvice',
            name='proadv_age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='professionaladvice',
            name='proadv_ethnic',
            field=models.CharField(blank=True, choices=[('1', '汉族'), ('2', '少数民族'), ('3', '其他')], max_length=1, verbose_name='民族'),
        ),
        migrations.AlterField(
            model_name='professionaladvice',
            name='proadv_from',
            field=models.CharField(choices=[('1', '社工发现'), ('2', '本人求助'), ('3', '他人求助'), ('4', '他人介绍'), ('5', '机构转介'), ('6', '其    他')], max_length=1, verbose_name='个案来源'),
        ),
        migrations.AlterField(
            model_name='professionaladvice',
            name='proadv_marriage',
            field=models.CharField(blank=True, choices=[('1', '未婚'), ('2', '已婚'), ('3', '离异'), ('4', '丧偶')], max_length=1, verbose_name='婚姻状况'),
        ),
        migrations.AlterField(
            model_name='professionaladvice',
            name='proadv_political_status',
            field=models.CharField(blank=True, choices=[('1', '中共党员'), ('2', '民主党派成员'), ('3', '共青团员'), ('4', '群众'), ('5', '其他')], max_length=1, verbose_name='政治面貌'),
        ),
        migrations.AlterField(
            model_name='professionaladvice',
            name='proadv_question_content',
            field=models.TextField(verbose_name='咨询内容'),
        ),
        migrations.AlterField(
            model_name='professionaladvice',
            name='proadv_rescue_methods',
            field=models.CharField(choices=[('1', '来    信'), ('2', '来    电'), ('3', '面    访'), ('4', '网上求助'), ('5', '其    他')], max_length=1, verbose_name='求助方法'),
        ),
        migrations.AlterField(
            model_name='professionaladvice',
            name='proadv_sex',
            field=models.CharField(choices=[('1', '男'), ('2', '女')], max_length=1, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='professionaladvice',
            name='proadv_status',
            field=models.BooleanField(default=True, verbose_name='个案完成状态'),
        ),
    ]
