# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180228_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionaladvice',
            name='proadv_serv_type',
            field=models.CharField(choices=[('1', '面谈'), ('2', '电访'), ('3', '其他')], max_length=1, verbose_name='服务方式'),
        ),
    ]
