# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180303_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='user_information_volunteer',
            field=models.BooleanField(default=False, verbose_name='志愿者'),
        ),
    ]
