# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20180228_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionaladvice',
            name='proadv_status',
            field=models.BooleanField(default=False, verbose_name='个案完成状态'),
        ),
    ]
