# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20180303_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='user_information_email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='电邮'),
        ),
    ]
