# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 05:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20180303_1344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinformation',
            options={},
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='campaign_person',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='campaign_volunteer',
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='user_information_sex',
            field=models.CharField(default=1, max_length=1, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='user_information_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
