# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20180228_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignsignup',
            name='campaign_info',
            field=models.ManyToManyField(blank=True, null=True, to='api.Campaign', verbose_name='公益活动信息'),
        ),
        migrations.AlterField(
            model_name='campaignsignup',
            name='campaign_person',
            field=models.ManyToManyField(blank=True, null=True, to='api.CampaignPerson', verbose_name='报名人员名单'),
        ),
        migrations.AlterField(
            model_name='campaignsignup',
            name='campaign_volunteer',
            field=models.ManyToManyField(blank=True, null=True, to='api.VolunteerInformation', verbose_name='报名志愿者名单'),
        ),
    ]
