# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 05:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20180303_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinformation',
            options={'verbose_name_plural': '用户基本信息'},
        ),
    ]
