# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 05:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20180303_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerinformation',
            name='volinfo_name',
        ),
    ]
