# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 06:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20180228_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignsignup',
            name='campaign_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Campaign', verbose_name='公益活动信息'),
        ),
    ]
