# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 06:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_volunteerinformation_volinfo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerinformation',
            name='volinfo_cellphone',
        ),
        migrations.RemoveField(
            model_name='volunteerinformation',
            name='volinfo_sex',
        ),
    ]
