# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 06:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20180303_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abilitytraining',
            name='volunteers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='报名志愿者名单'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='user_information_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='姓名'),
        ),
    ]
