# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20180228_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignsignup',
            name='campaign_info',
        ),
        migrations.RemoveField(
            model_name='campaignsignup',
            name='campaign_person',
        ),
        migrations.RemoveField(
            model_name='campaignsignup',
            name='campaign_volunteer',
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_person',
            field=models.ManyToManyField(blank=True, to='api.CampaignPerson', verbose_name='报名人员名单'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_volunteer',
            field=models.ManyToManyField(blank=True, to='api.VolunteerInformation', verbose_name='报名志愿者名单'),
        ),
        migrations.DeleteModel(
            name='CampaignSignUp',
        ),
    ]
