# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 06:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20180303_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='abilitytraining',
            name='at_remain',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='剩余可报名人数'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_person',
            field=models.ManyToManyField(blank=True, related_name='campaign_members', to=settings.AUTH_USER_MODEL, verbose_name='报名人员名单'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_volunteer',
            field=models.ManyToManyField(blank=True, related_name='campaign_volunteers', to=settings.AUTH_USER_MODEL, verbose_name='报名志愿者名单'),
        ),
        migrations.AlterField(
            model_name='abilitytraining',
            name='at_counts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='可报名总人数'),
        ),
    ]
