# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20180228_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerinformation',
            name='volinfo_marriage',
            field=models.CharField(blank=True, choices=[('1', '未婚'), ('2', '已婚'), ('3', '离异'), ('4', '丧偶')], max_length=1, verbose_name='婚姻状况'),
        ),
        migrations.AlterField(
            model_name='volunteerinformation',
            name='volinfo_sex',
            field=models.CharField(choices=[('1', '男'), ('2', '女')], max_length=1, verbose_name='性别'),
        ),
    ]
