# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 06:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20180303_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='campaign_person',
            new_name='campaign_members',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='campaign_volunteer',
            new_name='campaign_volunteers',
        ),
    ]
