# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20180228_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerinformation',
            name='volinfo_age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='年龄'),
        ),
    ]
