# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20180303_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_status',
            field=models.BooleanField(default=True, verbose_name='活动状态'),
        ),
    ]
