# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_campaign_campaign_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleuploadimg',
            name='photo',
            field=models.ImageField(upload_to='static', verbose_name='图片'),
        ),
    ]
