# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 06:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20180228_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignperson',
            name='campaign_person_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaignperson', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
