# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20180304_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleuploadimg',
            name='photo',
            field=models.ImageField(upload_to='media', verbose_name='图片'),
        ),
    ]
