# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20180228_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionaladvice',
            name='proadv_case_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='个案编号'),
        ),
        migrations.AlterField(
            model_name='professionaladvice',
            name='proadv_date',
            field=models.DateField(blank=True, null=True, verbose_name='咨询日期'),
        ),
        migrations.AlterField(
            model_name='professionaladvice',
            name='proadv_serv_content',
            field=models.TextField(blank=True, null=True, verbose_name='服务内容'),
        ),
        migrations.AlterField(
            model_name='professionaladvice',
            name='proadv_serv_date',
            field=models.DateField(blank=True, null=True, verbose_name='服务日期'),
        ),
        migrations.AlterField(
            model_name='professionaladvice',
            name='proadv_serv_localtion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='服务地点'),
        ),
        migrations.AlterField(
            model_name='professionaladvice',
            name='proadv_serv_time',
            field=models.TimeField(blank=True, null=True, verbose_name='服务时间'),
        ),
        migrations.AlterField(
            model_name='professionaladvice',
            name='proadv_serv_type',
            field=models.CharField(blank=True, choices=[('1', '面谈'), ('2', '电访'), ('3', '其他')], max_length=1, null=True, verbose_name='服务方式'),
        ),
        migrations.AlterField(
            model_name='professionaladvice',
            name='proadv_sw_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='社工姓名'),
        ),
    ]
