# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 00:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20180304_0759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singleuploadimg',
            old_name='photo',
            new_name='photo_path',
        ),
    ]
