# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 01:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20180304_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerinformation',
            name='volinfo_email',
        ),
    ]
