# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20180312_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyqa',
            name='qa_o2o',
            field=models.CharField(choices=[('1', '线上'), ('2', '线下')], default=1, max_length=1, verbose_name='线上线下回复'),
        ),
        migrations.AlterField(
            model_name='policyqa',
            name='qa_type',
            field=models.CharField(choices=[('1', '居住证及相关'), ('2', '户籍及相关'), ('3', '计生及相关'), ('4', '住房及相关'), ('5', '子女教育及相关'), ('6', '积分制及相关'), ('7', '综合类（多种问题）')], default=1, max_length=1, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='professionaladvice',
            name='proadv_question_type',
            field=models.CharField(blank=True, choices=[('1', '亲子关系问题'), ('2', '婚姻问题'), ('3', '家庭纠纷'), ('4', '经济问题'), ('5', '职业问题'), ('6', '住屋问题'), ('7', '家庭暴力致伤/死(受害对象: 子女 / 配偶 / 老人 / 其它______)'), ('8', '个人精神/情绪问题'), ('9', '个人行为问题(吸毒/酒/赌博)'), ('10', '恋爱/交友问题'), ('11', '患病/复康问题(病类)'), ('12', '未婚怀孕'), ('13', '收养'), ('14', '其它')], default=14, max_length=50, verbose_name='咨询问题类型'),
        ),
    ]
