# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_singleuploadimg_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='abilitytraining',
            name='at_update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='professionaladvice',
            name='proadv_update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='volunteerinformation',
            name='volinfo_update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='singleuploadimg',
            name='upload_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
