# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20180313_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='user_information_update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
