# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20180316_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerinformation',
            name='volinfo_idcard_type',
            field=models.CharField(choices=[('1', '身份证'), ('2', '护照'), ('3', '警官证'), ('4', '军官证')], default='1', max_length=10, verbose_name='证件类型'),
        ),
    ]
