# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 06:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20180316_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerinformation',
            name='volinfo_idcard_type',
            field=models.CharField(choices=[('1', '身份证'), ('2', '护照'), ('3', '警官证'), ('4', '军官证')], default='1', max_length=10, null=True, verbose_name='证件类型'),
        ),
        migrations.AlterField(
            model_name='volunteerinformation',
            name='volinfo_marriage',
            field=models.CharField(choices=[('1', '未婚'), ('2', '已婚'), ('3', '离异'), ('4', '丧偶')], default='1', max_length=1, null=True, verbose_name='婚姻状况'),
        ),
        migrations.AlterField(
            model_name='volunteerinformation',
            name='volinfo_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='平台用户'),
        ),
    ]
