# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 17:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20180316_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='user_information_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='volunteerinformation',
            name='volinfo_service_date',
            field=models.CharField(blank=True, choices=[('1', '法定休息日'), ('2', '工作日'), ('3', '不限')], default='1', max_length=50, verbose_name='志愿服务时间'),
        ),
    ]
