# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-17 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20180317_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyqa',
            name='qa_answer_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='回答时间'),
        ),
        migrations.AlterField(
            model_name='professionaladvice',
            name='proadv_question_type',
            field=models.CharField(blank=True, choices=[('1', '亲子关系问题'), ('2', '婚姻问题'), ('3', '家庭纠纷'), ('4', '经济问题'), ('5', '职业问题'), ('6', '住屋问题'), ('7', '家庭暴力致伤/死(受害对象:子女/配偶/老人/其它'), ('8', '个人精神/情绪问题'), ('9', '个人行为问题(吸毒/酒/赌博)'), ('10', '恋爱/交友问题'), ('11', '患病/复康问题(病类)'), ('12', '未婚怀孕'), ('13', '收养'), ('14', '其它')], default=14, max_length=50, verbose_name='咨询问题类型'),
        ),
    ]
