# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-18 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20180417_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyqa',
            name='qa_answer_date',
            field=models.DateTimeField(auto_now=True, verbose_name='回答时间'),
        ),
    ]
