# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-18 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20180418_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerinformation',
            name='volinfo_service_time',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='志愿活动认证时数'),
        ),
    ]
